config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :achievements do
    member do
      get 'assign'
    end
  end

  resources :totals
  resources :sections
end

app/models/Achievement.rb
class Achievement < ActiveRecord::Base
  validates :name, presence: true
  validates :prize, presence: true, numericality: true
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  validates :name, presence: true
  validates :prize, presence: true, numericality: true

  has_many :achievement_relations
  has_many :sections,
           through: :achievement_relations

  has_many :achievement_connections
  has_many :users,
           through: :achievement_connections

  def to_s
    name
  end
end

app/models/achievement_connection.rb
class AchievementConnection < ActiveRecord::Base
  belongs_to :achievement
  belongs_to :user
end

app/models/achievement_relation.rb
class AchievementRelation < ActiveRecord::Base
  belongs_to :achievement
  belongs_to :section
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :achievement_relations
  has_many :achievements,
           through: :achievement_relations

  validates :name, presence: true
  #https://github.com/plataformatec/simple_form
end

app/models/total.rb
class Total < ActiveRecord::Base
  belongs_to :user

end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

  def index
    achievements = Achievement.all
    sections = Section.all
    user = User.current
    render locals:{achievements: achievements, user:user, sections: sections}
  end

  def new
    achievement = Achievement.new
    render locals:{achievement: achievement}
  end

  def create
    achievement = Achievement.new(params_counter)

    achievement.save
    redirect_to achievements_path

  end

  def show
    achievement = Achievement.find(params[:id])
    render locals: {achievement: achievement}
  end

  def edit
    achievement = Achievement.find(params[:id])
    render locals: {achievement: achievement}
  end

  def update
    achievement= Achievement.find(params[:id])

    if achievement.update(params_counter)
      redirect_to achievements_path
    else
      render 'edit'
    end

  end

  def destroy
    achievement = Achievement.find(params[:id])

    unless achievement.destroy
      flash[:error] = 'ошибка удаления'
    end

    redirect_to achievements_path
  end

  def assign

  end

  def params_counter
    params.
        require(:achievement).permit(:name, :description, :prize, :action, :status)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def new
    section = Section.new
    achievements = Achievement.all
    render locals: {section: section, achievements: achievements}
  end

  def create
    unless Section.create(section_params)
      flash[:error] = 'Не удалось сохранить группу'
    end
    redirect_to achievements_path
  end

  def show
    render locals: {section: Section.find(params[:id])}
  end

  def update
    section = Section.find(params[:id])

    if section.update(section_params)
      redirect_to section
    else
      render 'edit'
    end
  end

  def edit
    section = Section.find(params[:id])
    achievements = Achievement.all
    render locals: {section: section, achievements: achievements}
  end

  def destroy
    section = Section.find(params[:id])
    unless section.destroy
      flash[:error] = 'ошибка удаления'
    end
    redirect_to achievements_path
  end

  private

  def section_params
    params.require(:section).permit(:name, achievement_ids: [])
  end
end

app/controllers/totals_controller.rb
class TotalsController < ApplicationController

  def index

    user = User.current
    if(user.admin)
      totals = Total.all
      render locals: {totals: totals, user: user}
    else
      total = Total.find_by(user_id: user.id)
      render locals: {total: total, user: user}
    end

    end

end

app/views/achievements/_form.html.slim
= form_with model: achievement do |form|
  table
    tr
      td  = form.label :name
      td  = form.text_field :name
    tr
      td  = form.label :description
      td  = form.text_field :description
    tr
      td  = form.label :prize
      td  = form.text_field :prize
    tr
      td  = form.label :action
      td  = form.text_field :action
    tr
      td  = form.label :status
      td автоматическое присваивание
      td  = form.check_box :status


  br
  = form.submit

app/views/achievements/assign.html.slim
h1
  |manual assign

=simple_form_for achievement do |form|
  table
    tr
      td  = form.input :name
    tr
      td = form.association :users, as: :check_boxes
  =form.button :submit
br

=link_to '    назад', achievements_path

app/views/achievements/edit.html.slim
h1
  |Редактировать
= form_with(model: achievement, local: true) do |form|

  -if achievement.errors.any?
    div
      -id="error_explanation"
    h2
      =pluralize(achievement.errors.count, "error")
    ul
      -achievement.errors.full_messages.each do |msg|
        li = msg
        end

  end

=render 'form', achievement:achievement

  br
  = form.submit
br
=link_to 'назад', achievements_path

app/views/achievements/index.html.slim
h1
  |Достижения

table
  tr
    td name
    td description
    td prize
    td action
    td status
    td show
    - if user.admin?
      td edit
      td delete
      td assign
  -achievements.each do |achievement|
    tr
      td =achievement.name
      td =achievement.description
      td = achievement.prize
      td = achievement.action
      td = achievement.status
      td =link_to 'show' , achievement_path(achievement)
      - if user.admin
        td =link_to 'edit', edit_achievement_path(achievement)
        td =link_to 'del', achievement_path(achievement), method: :delete
        - if !achievement.status?
            td =link_to 'assign', assign_achievement_path(achievement)
br
- if user.admin
  =link_to 'Создать новое достижение', new_achievement_path
br
br
br
h1
  |Группы достижений

table
  tr
    td name
    td achievements
    - if user.admin
      td edit
      td delete
  - sections.each do |section|
    tr
      td= section.name
      td= section.achievements.join(', ')
      - if user.admin
        td= link_to 'редактировать', edit_section_path(section)
        td= link_to 'удалить', section_path(section), method: :delete
br
- if user.admin?
  = link_to 'Создать новую группу', new_section_path

app/views/achievements/new.html.slim
h1
  |новое достижение
= error_messages_for achievement

=render 'form', achievement:achievement
br

=link_to '    назад', achievements_path

app/views/achievements/show.html.slim
h1
  =achievement.name
table
  tr
    td = achievement.description
  tr
    td = achievement.prize
  tr
    td = achievement.action
  tr
    td = achievement.from
  tr
    td = achievement.counter
  tr
    td = achievement.rank
  tr
    td = achievement.status

br
br
=link_to 'назад', achievements_path

app/views/sections/_form.html.slim
= simple_form_for section do |form|
  table
    tr
      td  = form.input :name
    tr
      td = form.association :achievements, as: :check_boxes
  = form.button :submit

app/views/sections/edit.html.slim
h1
  |Редактировать
= form_with(model: section, local: true) do |form|

  -if section.errors.any?
    div
      -id="error_explanation"
    h2
      =pluralize(section.errors.count, "error")
    ul
      -section.errors.full_messages.each do |msg|
        li = msg
        end

  end


=render 'form' , section: section

br
=link_to 'назад', achievements_path

app/views/sections/new.html.slim
h1
  |новая группа достижений
= error_messages_for section

=render 'form' , section: section
br
=link_to '    назад', achievements_path

app/views/sections/show.html.slim
h1
  =section.name
br
h2
  =section.achievements.join(', ')

br
br
=link_to 'назад', achievements_path

app/views/totals/index.html.slim
h1
  -if(!user.admin)
    | Результаты пользователя:
    =user.login
  -else
    | Результаты пользователей:

table
  tr
    -if(user.admin)
      td user

    td likes count
    td comments count
    td rediscoveredTaskCount
    td created tasks
    td tasks execute time
    td pages edited of wiki

  -if user.admin
    -totals.each do |total|
      tr
        td = User.find_by(id: total.user_id).login
        td = total.likes
        td = total.comments
        td = total.rediscoveredTaskCount
        td = total.createTaskCount
        td = total.taskTimeCounter
        td = total.wikiPagesEditCount
      end
  -else
    tr
      td = total.likes
      td = total.comments
      td = total.rediscoveredTaskCount
      td = total.createTaskCount
      td = total.taskTimeCounter
      td = total.wikiPagesEditCount